### ISSUE TITLE
Rename COMC-0654-0430 (in P6) to avoid the term "mini-survey"

### ISSUE THREAD

**Issue by drphilmarshall** [lsst-dm/dmtn-232#22]
@womullan 

Current Top Milestones list includes:

2024-06-11 : **Mini-Survey 2 Complete** (COMC-0654-0430)

The Science Validation surveys in commissioning are not "mini-surveys", and SIT-COM does not use the term. Since the Top Milestones are now being used by the community, we should try and be as clear and consistent in our terminology as possible, to avoid confusion.

After discussion with Keith, Chuck, Leanne and Zeljko, we concluded that COMC-0654-0430 needs re-naming in P6 to :

2024-06-11 : **Science Validation Survey(s) Complete"** (COMC-0654-0430) 

Note that the top milestone should be the end of SV data taking, not just survey number 2 - especially given that the actual SV program when it is executed may not have 2 component surveys at all! So theres a small check to do that COMC-0654-0430 really is supposed to mark the overall end of SV.

Would you be able to orchestrate the above change, please? Thanks!

**Comment by womullan** [comment]
Checking with Kevin if i need an LCR

**Comment by womullan** [comment]
Kevin says this can be done directly

**Comment by womullan** [comment]
https://project.lsst.org/groups/ccb/node/5156
On 10 Aug 2022, 12:31 -0700, lsst-dm/dmtn-232 ***@***.***>, wrote:

urrent Top Milestones list includes:

2024-06-11 : Mini-Survey 2 Complete (COMC-0654-0430)

The Science Validation surveys in commissioning are not "mini-surveys", and SIT-COM does not use the term. Since the Top Milestones are now being used by the community, we should try and be as clear and consistent in our terminology as possible, to avoid confusion.

After discussion with Keith, Chuck, Leanne and Zeljko, we concluded that COMC-0654-0430 needs re-naming in P6 to :

2024-06-11 : Science Validation Survey(s) Complete" (COMC-0654-0430)

Note that the top milestone should be the end of SV data taking, not just survey number 2 - especially given that the actual SV program when it is executed may not have 2 component surveys at all! So theres a small check to do that COMC-0654-0430 really is supposed to mark the overall end of SV.

**Comment by drphilmarshall** [comment]
Great, thanks @womullan ! I love a good LCR.

**Comment by drphilmarshall** [comment]
Hooray! Thanks Wil :-)
________________________________
